"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-09 06:35:28.086087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_year',
    sa.Column('academic_year_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PLANNED', 'ACTIVE', 'CLOSED')", name='ck_ay_status'),
    sa.CheckConstraint('end_date >= start_date', name='ck_ay_dates'),
    sa.PrimaryKeyConstraint('academic_year_id'),
    sa.UniqueConstraint('label')
    )
    op.create_index('uq_ay_single_active', 'academic_year', ['status'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_table('department',
    sa.Column('department_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('department_id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role',
    sa.Column('role_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.CheckConstraint("code IN ('STUDENT', 'PROFESSOR', 'HOD', 'PRINCIPAL', 'ADMIN')", name='ck_role_code'),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('room',
    sa.Column('room_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('room_code', sa.String(length=40), nullable=False),
    sa.Column('building', sa.String(length=100), nullable=True),
    sa.Column('floor_label', sa.String(length=40), nullable=True),
    sa.Column('room_type', sa.String(length=40), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('capacity IS NULL OR capacity > 0', name='ck_room_capacity'),
    sa.PrimaryKeyConstraint('room_id'),
    sa.UniqueConstraint('room_code')
    )
    op.create_table('user_account',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('college_email', sa.String(length=254), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('auth_subject', sa.String(length=255), nullable=True),
    sa.Column('timezone_id', sa.String(length=64), server_default='Asia/Kolkata', nullable=False),
    sa.Column('account_status', sa.String(length=20), nullable=False),
    sa.Column('token_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("account_status IN ('INVITED', 'ACTIVE', 'SUSPENDED', 'DISABLED')", name='ck_user_status'),
    sa.CheckConstraint('college_email = lower(college_email)', name='ck_user_email_normalized'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('auth_subject'),
    sa.UniqueConstraint('college_email')
    )
    op.create_table('account_token',
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(length=24), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("purpose IN ('INVITATION', 'PASSWORD_RESET')", name='ck_token_purpose'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('audit_event',
    sa.Column('audit_event_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=80), nullable=True),
    sa.Column('target_id', sa.String(length=100), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('audit_event_id')
    )
    op.create_index('ix_audit_actor', 'audit_event', ['actor_user_id', sa.literal_column('occurred_at DESC')], unique=False)
    op.create_index('ix_audit_occurred', 'audit_event', [sa.literal_column('occurred_at DESC')], unique=False)
    op.create_table('batch',
    sa.Column('batch_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('cohort_label', sa.String(length=40), nullable=False),
    sa.Column('division_label', sa.String(length=20), nullable=False),
    sa.Column('program_year', sa.SmallInteger(), nullable=False),
    sa.Column('parent_batch_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('parent_batch_id IS NULL OR parent_batch_id <> batch_id', name='ck_batch_parent'),
    sa.CheckConstraint('program_year > 0', name='ck_batch_year'),
    sa.ForeignKeyConstraint(['department_id'], ['department.department_id'], ),
    sa.ForeignKeyConstraint(['parent_batch_id'], ['batch.batch_id'], ),
    sa.PrimaryKeyConstraint('batch_id'),
    sa.UniqueConstraint('department_id', 'code', name='uq_batch_code'),
    sa.UniqueConstraint('department_id', 'cohort_label', 'division_label', name='uq_batch_cohort_div')
    )
    op.create_table('course',
    sa.Column('course_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=True),
    sa.Column('course_code', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.department_id'], ),
    sa.PrimaryKeyConstraint('course_id'),
    sa.UniqueConstraint('course_code')
    )
    op.create_table('entity_alias',
    sa.Column('alias_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=16), nullable=False),
    sa.Column('alias', sa.String(length=120), nullable=False),
    sa.Column('alias_normalized', sa.String(length=120), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("entity_type IN ('COURSE', 'STAFF', 'ROOM', 'BATCH')", name='ck_alias_type'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('alias_id'),
    sa.UniqueConstraint('entity_type', 'alias_normalized', 'entity_id', name='uq_alias')
    )
    op.create_index('ix_alias_lookup', 'entity_alias', ['entity_type', 'alias_normalized'], unique=False)
    op.create_table('institution_config',
    sa.Column('config_id', sa.SmallInteger(), nullable=False),
    sa.Column('institution_name', sa.String(length=200), nullable=True),
    sa.Column('week_start_day', sa.SmallInteger(), nullable=True),
    sa.Column('lunch_boundary', sa.Time(), nullable=True),
    sa.Column('working_hours_start', sa.Time(), nullable=True),
    sa.Column('working_hours_end', sa.Time(), nullable=True),
    sa.Column('next_class_lookahead_days', sa.SmallInteger(), server_default='7', nullable=False),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('config_id = 1', name='ck_config_single_row'),
    sa.CheckConstraint('next_class_lookahead_days BETWEEN 0 AND 14', name='ck_config_lookahead'),
    sa.CheckConstraint('week_start_day IS NULL OR week_start_day BETWEEN 1 AND 7', name='ck_config_week'),
    sa.CheckConstraint('working_hours_start IS NULL OR working_hours_end IS NULL OR working_hours_end > working_hours_start', name='ck_config_hours'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('config_id')
    )
    op.create_table('institutional_timetable',
    sa.Column('timetable_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.BigInteger(), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=True),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('original_file_key', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('file_format', sa.String(length=16), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processing_status', sa.String(length=24), nullable=False),
    sa.Column('validation_summary', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('parser_version', sa.String(length=80), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('effective_from_raw', sa.String(length=120), nullable=True),
    sa.Column('term_label', sa.String(length=80), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('client_request_id', sa.String(length=64), nullable=True),
    sa.Column('data_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("processing_status IN ('QUEUED', 'PROCESSING', 'NEEDS_REVIEW', 'READY', 'FAILED', 'UNUSABLE')", name='ck_itt_status'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.academic_year_id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.department_id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('timetable_id')
    )
    op.create_index('ix_itt_status', 'institutional_timetable', ['processing_status'], unique=False)
    op.create_index('ix_itt_year_uploaded', 'institutional_timetable', ['academic_year_id', sa.literal_column('uploaded_at DESC')], unique=False)
    op.create_index('uq_itt_client_req', 'institutional_timetable', ['uploaded_by_user_id', 'client_request_id'], unique=True, postgresql_where=sa.text('client_request_id IS NOT NULL'))
    op.create_table('notification',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index('ix_notif_user_created', 'notification', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('personal_timetable',
    sa.Column('timetable_id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('original_file_key', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('file_format', sa.String(length=16), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processing_status', sa.String(length=24), nullable=False),
    sa.Column('validation_summary', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('parser_version', sa.String(length=80), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('effective_from_raw', sa.String(length=120), nullable=True),
    sa.Column('term_label', sa.String(length=80), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('client_request_id', sa.String(length=64), nullable=True),
    sa.Column('data_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("processing_status IN ('QUEUED', 'PROCESSING', 'NEEDS_REVIEW', 'READY', 'FAILED', 'UNUSABLE')", name='ck_ptt_status'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('timetable_id'),
    sa.UniqueConstraint('timetable_id', 'owner_user_id', name='uq_ptt_id_owner')
    )
    op.create_index('ix_ptt_owner_uploaded', 'personal_timetable', ['owner_user_id', sa.literal_column('uploaded_at DESC')], unique=False)
    op.create_index('ix_ptt_status', 'personal_timetable', ['processing_status'], unique=False)
    op.create_index('uq_ptt_client_req', 'personal_timetable', ['owner_user_id', 'client_request_id'], unique=True, postgresql_where=sa.text('client_request_id IS NOT NULL'))
    op.create_table('push_device',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expo_push_token', sa.String(length=200), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id'),
    sa.UniqueConstraint('expo_push_token')
    )
    op.create_index(op.f('ix_push_device_user_id'), 'push_device', ['user_id'], unique=False)
    op.create_table('refresh_token',
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.UUID(), nullable=True),
    sa.Column('device_label', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_refresh_user', 'refresh_token', ['user_id'], unique=False)
    op.create_table('saved_search',
    sa.Column('saved_search_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('query_text', sa.String(length=300), nullable=True),
    sa.Column('intent', sa.String(length=40), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('saved_search_id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_saved_search_name')
    )
    op.create_index(op.f('ix_saved_search_user_id'), 'saved_search', ['user_id'], unique=False)
    op.create_table('search_history',
    sa.Column('search_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.String(length=300), nullable=False),
    sa.Column('intent', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('domain', sa.String(length=20), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('search_id')
    )
    op.create_index('ix_sh_user_created', 'search_history', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('staff',
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('staff_status', sa.String(length=24), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=True),
    sa.Column('short_code', sa.String(length=20), nullable=True),
    sa.Column('designation', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("staff_status IN ('ACTIVE', 'INACTIVE')", name='ck_staff_status'),
    sa.ForeignKeyConstraint(['department_id'], ['department.department_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('staff_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('student',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('uid', sa.String(length=64), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=True),
    sa.Column('student_status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("student_status IN ('ACTIVE', 'PAUSED', 'WITHDRAWN', 'GRADUATED')", name='ck_student_status'),
    sa.ForeignKeyConstraint(['department_id'], ['department.department_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('uid'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('assigned_by_user_id', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['user_account.user_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('institutional_timetable_section',
    sa.Column('timetable_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('program_level', sa.String(length=40), nullable=True),
    sa.Column('divisions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('is_tentative', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('header_raw', sa.Text(), nullable=True),
    sa.Column('legend', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('extraction_method', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['timetable_id'], ['institutional_timetable.timetable_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('section_id')
    )
    op.create_index(op.f('ix_institutional_timetable_section_timetable_id'), 'institutional_timetable_section', ['timetable_id'], unique=False)
    op.create_table('institutional_timetable_settings',
    sa.Column('settings_id', sa.SmallInteger(), nullable=False),
    sa.Column('default_timetable_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.CheckConstraint('settings_id = 1', name='ck_its_single_row'),
    sa.ForeignKeyConstraint(['default_timetable_id'], ['institutional_timetable.timetable_id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('settings_id')
    )
    op.create_table('personal_timetable_section',
    sa.Column('timetable_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('program_level', sa.String(length=40), nullable=True),
    sa.Column('divisions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('is_tentative', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('header_raw', sa.Text(), nullable=True),
    sa.Column('legend', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('extraction_method', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['timetable_id'], ['personal_timetable.timetable_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('section_id')
    )
    op.create_index(op.f('ix_personal_timetable_section_timetable_id'), 'personal_timetable_section', ['timetable_id'], unique=False)
    op.create_table('processing_job',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=20), nullable=False),
    sa.Column('institutional_timetable_id', sa.UUID(), nullable=True),
    sa.Column('personal_timetable_id', sa.UUID(), nullable=True),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='3', nullable=False),
    sa.Column('worker_id', sa.String(length=80), nullable=True),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('progress', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(domain = 'INSTITUTIONAL' AND institutional_timetable_id IS NOT NULL AND personal_timetable_id IS NULL) OR (domain = 'PERSONAL' AND personal_timetable_id IS NOT NULL AND institutional_timetable_id IS NULL)", name='ck_job_one_target'),
    sa.CheckConstraint("domain IN ('INSTITUTIONAL', 'PERSONAL')", name='ck_job_domain'),
    sa.CheckConstraint("status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED')", name='ck_job_status'),
    sa.ForeignKeyConstraint(['institutional_timetable_id'], ['institutional_timetable.timetable_id'], ),
    sa.ForeignKeyConstraint(['personal_timetable_id'], ['personal_timetable.timetable_id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index('ix_job_requested_by', 'processing_job', ['requested_by_user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_job_status_created', 'processing_job', ['status', 'created_at'], unique=False)
    op.create_table('student_academic_history',
    sa.Column('history_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.BigInteger(), nullable=False),
    sa.Column('year_of_study', sa.SmallInteger(), nullable=False),
    sa.Column('semester', sa.SmallInteger(), nullable=True),
    sa.Column('department_id', sa.BigInteger(), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('confirmed_by_staff_id', sa.UUID(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'REPEATING', 'PAUSED', 'PROMOTED', 'WITHDRAWN', 'GRADUATED', 'CLOSED')", name='ck_sah_status'),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name='ck_sah_dates'),
    sa.CheckConstraint('semester IS NULL OR semester > 0', name='ck_sah_sem'),
    sa.CheckConstraint('year_of_study > 0', name='ck_sah_year'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.academic_year_id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.batch_id'], ),
    sa.ForeignKeyConstraint(['confirmed_by_staff_id'], ['staff.staff_id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.department_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index('ix_sah_student_from', 'student_academic_history', ['student_id', sa.literal_column('effective_from DESC')], unique=False)
    op.create_index('uq_sah_one_open', 'student_academic_history', ['student_id'], unique=True, postgresql_where=sa.text('effective_to IS NULL'))
    op.create_table('user_preference',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('personal_primary_timetable_id', sa.UUID(), nullable=True),
    sa.Column('selection_mode', sa.String(length=24), server_default='REMEMBER_LAST', nullable=False),
    sa.Column('last_active_domain', sa.String(length=20), nullable=True),
    sa.Column('last_personal_timetable_id', sa.UUID(), nullable=True),
    sa.Column('last_institutional_timetable_id', sa.UUID(), nullable=True),
    sa.Column('notify_official_timetable', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notify_processing', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('search_history_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('theme', sa.String(length=10), server_default='system', nullable=False),
    sa.Column('time_format_24h', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("last_active_domain IS NULL OR last_active_domain IN ('INSTITUTIONAL', 'PERSONAL')", name='ck_pref_domain'),
    sa.CheckConstraint("selection_mode IN ('REMEMBER_LAST', 'ALWAYS_USE_PRIMARY')", name='ck_pref_mode'),
    sa.ForeignKeyConstraint(['last_institutional_timetable_id'], ['institutional_timetable.timetable_id'], ),
    sa.ForeignKeyConstraint(['last_personal_timetable_id', 'user_id'], ['personal_timetable.timetable_id', 'personal_timetable.owner_user_id'], name='fk_pref_last_personal_owned'),
    sa.ForeignKeyConstraint(['personal_primary_timetable_id', 'user_id'], ['personal_timetable.timetable_id', 'personal_timetable.owner_user_id'], name='fk_pref_primary_owned'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('validation_finding',
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=20), nullable=False),
    sa.Column('institutional_timetable_id', sa.UUID(), nullable=True),
    sa.Column('personal_timetable_id', sa.UUID(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('entry_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(domain = 'INSTITUTIONAL' AND institutional_timetable_id IS NOT NULL AND personal_timetable_id IS NULL) OR (domain = 'PERSONAL' AND personal_timetable_id IS NOT NULL AND institutional_timetable_id IS NULL)", name='ck_vf_one_target'),
    sa.CheckConstraint("domain IN ('INSTITUTIONAL', 'PERSONAL')", name='ck_vf_domain'),
    sa.CheckConstraint("severity IN ('BLOCKING','PAGE_ERROR','CRITICAL','WARNING','INFO','SECTION_FLAG','METADATA_WARNING')", name='ck_vf_severity'),
    sa.ForeignKeyConstraint(['institutional_timetable_id'], ['institutional_timetable.timetable_id'], ),
    sa.ForeignKeyConstraint(['personal_timetable_id'], ['personal_timetable.timetable_id'], ),
    sa.PrimaryKeyConstraint('finding_id')
    )
    op.create_index('ix_vf_itt', 'validation_finding', ['institutional_timetable_id'], unique=False)
    op.create_index('ix_vf_ptt', 'validation_finding', ['personal_timetable_id'], unique=False)
    op.create_table('institutional_timetable_entry',
    sa.Column('timetable_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.Column('course_id', sa.BigInteger(), nullable=True),
    sa.Column('batch_id', sa.BigInteger(), nullable=True),
    sa.Column('staff_id', sa.UUID(), nullable=True),
    sa.Column('room_id', sa.BigInteger(), nullable=True),
    sa.Column('course_label_raw', sa.String(length=200), nullable=True),
    sa.Column('batch_label_raw', sa.String(length=100), nullable=True),
    sa.Column('staff_label_raw', sa.String(length=200), nullable=True),
    sa.Column('room_label_raw', sa.String(length=100), nullable=True),
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('entry_kind', sa.String(length=16), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=True),
    sa.Column('class_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('time_label_raw', sa.String(length=120), nullable=True),
    sa.Column('course_name_resolved', sa.String(length=200), nullable=True),
    sa.Column('staff_name_resolved', sa.String(length=200), nullable=True),
    sa.Column('raw_extracted_text', sa.Text(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_region', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('verification_status', sa.String(length=24), nullable=False),
    sa.Column('validation_messages', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('is_tentative', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('extraction_method', sa.String(length=20), nullable=False),
    sa.Column('is_corrected', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("entry_kind IN ('CLASS', 'BREAK', 'ACTIVITY')", name='ck_ite_kind'),
    sa.CheckConstraint("verification_status IN ('VERIFIED', 'UNVERIFIED', 'INCOMPLETE', 'REJECTED')", name='ck_ite_vstatus'),
    sa.CheckConstraint('confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)', name='ck_ite_conf'),
    sa.CheckConstraint('day_of_week IS NULL OR day_of_week BETWEEN 1 AND 7', name='ck_ite_dow'),
    sa.CheckConstraint('source_page IS NULL OR source_page > 0', name='ck_ite_page'),
    sa.CheckConstraint('start_time IS NULL OR end_time IS NULL OR end_time > start_time', name='ck_ite_times'),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.batch_id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['institutional_timetable_section.section_id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ),
    sa.ForeignKeyConstraint(['timetable_id'], ['institutional_timetable.timetable_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.create_index('ix_ite_tt_batch', 'institutional_timetable_entry', ['timetable_id', 'batch_id'], unique=False)
    op.create_index('ix_ite_tt_course', 'institutional_timetable_entry', ['timetable_id', 'course_id'], unique=False)
    op.create_index('ix_ite_tt_date_start', 'institutional_timetable_entry', ['timetable_id', 'class_date', 'start_time'], unique=False)
    op.create_index('ix_ite_tt_dow_start', 'institutional_timetable_entry', ['timetable_id', 'day_of_week', 'start_time'], unique=False)
    op.create_index('ix_ite_tt_room', 'institutional_timetable_entry', ['timetable_id', 'room_id'], unique=False)
    op.create_index('ix_ite_tt_staff', 'institutional_timetable_entry', ['timetable_id', 'staff_id'], unique=False)
    op.create_table('personal_timetable_entry',
    sa.Column('timetable_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.Column('course_label', sa.String(length=200), nullable=True),
    sa.Column('batch_label', sa.String(length=100), nullable=True),
    sa.Column('professor_label', sa.String(length=200), nullable=True),
    sa.Column('room_label', sa.String(length=100), nullable=True),
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('entry_kind', sa.String(length=16), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=True),
    sa.Column('class_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('time_label_raw', sa.String(length=120), nullable=True),
    sa.Column('course_name_resolved', sa.String(length=200), nullable=True),
    sa.Column('staff_name_resolved', sa.String(length=200), nullable=True),
    sa.Column('raw_extracted_text', sa.Text(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_region', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('verification_status', sa.String(length=24), nullable=False),
    sa.Column('validation_messages', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('is_tentative', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('extraction_method', sa.String(length=20), nullable=False),
    sa.Column('is_corrected', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("entry_kind IN ('CLASS', 'BREAK', 'ACTIVITY')", name='ck_pte_kind'),
    sa.CheckConstraint("verification_status IN ('VERIFIED', 'UNVERIFIED', 'INCOMPLETE', 'REJECTED')", name='ck_pte_vstatus'),
    sa.CheckConstraint('confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)', name='ck_pte_conf'),
    sa.CheckConstraint('day_of_week IS NULL OR day_of_week BETWEEN 1 AND 7', name='ck_pte_dow'),
    sa.CheckConstraint('source_page IS NULL OR source_page > 0', name='ck_pte_page'),
    sa.CheckConstraint('start_time IS NULL OR end_time IS NULL OR end_time > start_time', name='ck_pte_times'),
    sa.ForeignKeyConstraint(['section_id'], ['personal_timetable_section.section_id'], ),
    sa.ForeignKeyConstraint(['timetable_id'], ['personal_timetable.timetable_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.create_index('ix_pte_tt_date_start', 'personal_timetable_entry', ['timetable_id', 'class_date', 'start_time'], unique=False)
    op.create_index('ix_pte_tt_dow_start', 'personal_timetable_entry', ['timetable_id', 'day_of_week', 'start_time'], unique=False)
    op.create_table('entry_correction',
    sa.Column('correction_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=20), nullable=False),
    sa.Column('institutional_entry_id', sa.UUID(), nullable=True),
    sa.Column('personal_entry_id', sa.UUID(), nullable=True),
    sa.Column('corrected_by_user_id', sa.UUID(), nullable=False),
    sa.Column('corrected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.CheckConstraint("(domain = 'INSTITUTIONAL' AND institutional_entry_id IS NOT NULL AND personal_entry_id IS NULL) OR (domain = 'PERSONAL' AND personal_entry_id IS NOT NULL AND institutional_entry_id IS NULL)", name='ck_ec_one_target'),
    sa.CheckConstraint("domain IN ('INSTITUTIONAL', 'PERSONAL')", name='ck_ec_domain'),
    sa.ForeignKeyConstraint(['corrected_by_user_id'], ['user_account.user_id'], ),
    sa.ForeignKeyConstraint(['institutional_entry_id'], ['institutional_timetable_entry.entry_id'], ),
    sa.ForeignKeyConstraint(['personal_entry_id'], ['personal_timetable_entry.entry_id'], ),
    sa.PrimaryKeyConstraint('correction_id')
    )
    op.create_index(op.f('ix_entry_correction_institutional_entry_id'), 'entry_correction', ['institutional_entry_id'], unique=False)
    op.create_index(op.f('ix_entry_correction_personal_entry_id'), 'entry_correction', ['personal_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entry_correction_personal_entry_id'), table_name='entry_correction')
    op.drop_index(op.f('ix_entry_correction_institutional_entry_id'), table_name='entry_correction')
    op.drop_table('entry_correction')
    op.drop_index('ix_pte_tt_dow_start', table_name='personal_timetable_entry')
    op.drop_index('ix_pte_tt_date_start', table_name='personal_timetable_entry')
    op.drop_table('personal_timetable_entry')
    op.drop_index('ix_ite_tt_staff', table_name='institutional_timetable_entry')
    op.drop_index('ix_ite_tt_room', table_name='institutional_timetable_entry')
    op.drop_index('ix_ite_tt_dow_start', table_name='institutional_timetable_entry')
    op.drop_index('ix_ite_tt_date_start', table_name='institutional_timetable_entry')
    op.drop_index('ix_ite_tt_course', table_name='institutional_timetable_entry')
    op.drop_index('ix_ite_tt_batch', table_name='institutional_timetable_entry')
    op.drop_table('institutional_timetable_entry')
    op.drop_index('ix_vf_ptt', table_name='validation_finding')
    op.drop_index('ix_vf_itt', table_name='validation_finding')
    op.drop_table('validation_finding')
    op.drop_table('user_preference')
    op.drop_index('uq_sah_one_open', table_name='student_academic_history', postgresql_where=sa.text('effective_to IS NULL'))
    op.drop_index('ix_sah_student_from', table_name='student_academic_history')
    op.drop_table('student_academic_history')
    op.drop_index('ix_job_status_created', table_name='processing_job')
    op.drop_index('ix_job_requested_by', table_name='processing_job')
    op.drop_table('processing_job')
    op.drop_index(op.f('ix_personal_timetable_section_timetable_id'), table_name='personal_timetable_section')
    op.drop_table('personal_timetable_section')
    op.drop_table('institutional_timetable_settings')
    op.drop_index(op.f('ix_institutional_timetable_section_timetable_id'), table_name='institutional_timetable_section')
    op.drop_table('institutional_timetable_section')
    op.drop_table('user_role')
    op.drop_table('student')
    op.drop_table('staff')
    op.drop_index('ix_sh_user_created', table_name='search_history')
    op.drop_table('search_history')
    op.drop_index(op.f('ix_saved_search_user_id'), table_name='saved_search')
    op.drop_table('saved_search')
    op.drop_index('ix_refresh_user', table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_index(op.f('ix_push_device_user_id'), table_name='push_device')
    op.drop_table('push_device')
    op.drop_index('uq_ptt_client_req', table_name='personal_timetable', postgresql_where=sa.text('client_request_id IS NOT NULL'))
    op.drop_index('ix_ptt_status', table_name='personal_timetable')
    op.drop_index('ix_ptt_owner_uploaded', table_name='personal_timetable')
    op.drop_table('personal_timetable')
    op.drop_index('ix_notif_user_created', table_name='notification')
    op.drop_table('notification')
    op.drop_index('uq_itt_client_req', table_name='institutional_timetable', postgresql_where=sa.text('client_request_id IS NOT NULL'))
    op.drop_index('ix_itt_year_uploaded', table_name='institutional_timetable')
    op.drop_index('ix_itt_status', table_name='institutional_timetable')
    op.drop_table('institutional_timetable')
    op.drop_table('institution_config')
    op.drop_index('ix_alias_lookup', table_name='entity_alias')
    op.drop_table('entity_alias')
    op.drop_table('course')
    op.drop_table('batch')
    op.drop_index('ix_audit_occurred', table_name='audit_event')
    op.drop_index('ix_audit_actor', table_name='audit_event')
    op.drop_table('audit_event')
    op.drop_table('account_token')
    op.drop_table('user_account')
    op.drop_table('room')
    op.drop_table('role')
    op.drop_table('department')
    op.drop_index('uq_ay_single_active', table_name='academic_year', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_table('academic_year')
    # ### end Alembic commands ###
