"""entry time_uncertain flag

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-09 06:52:42.886995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = "0002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutional_timetable_entry', sa.Column('time_uncertain', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('personal_timetable_entry', sa.Column('time_uncertain', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personal_timetable_entry', 'time_uncertain')
    op.drop_column('institutional_timetable_entry', 'time_uncertain')
    # ### end Alembic commands ###
