"""DEVELOPMENT-ONLY demo data. Refuses to run when ENVIRONMENT=production.

All names, codes and schedules here are invented sample data (they match the SYNTHETIC fixture
generated by app/devdata/synthetic.py). They are NOT the college's real timetable.

Usage:
    python -m app.seed            # add demo data to an empty database
    python -m app.seed --reset    # DROP everything, re-run migrations, then seed
    python -m app.seed --no-timetables
"""
from __future__ import annotations

import argparse
import os
import sys
import tempfile
from datetime import date, time

from sqlalchemy import select, text

from app.config import get_settings
from app.db import get_engine, session_factory
from app.enums import AccountStatus, Domain, HistoryStatus, RoleCode
from app.models import (
    AcademicYear,
    Batch,
    Course,
    Department,
    InstitutionConfig,
    Role,
    Room,
    Staff,
    Student,
    StudentAcademicHistory,
    UserAccount,
    UserPreference,
    UserRole,
)
from app.security.passwords import hash_password
from app.security.principal import load_principal

DEMO_PASSWORD = "Demo@12345"
DOMAIN = "demo.college.edu"


def _guard() -> None:
    if get_settings().is_production:
        sys.exit("Refusing to seed demo accounts: ENVIRONMENT=production.")


def reset_database() -> None:
    _guard()
    from alembic import command
    from alembic.config import Config

    with get_engine().begin() as c:
        c.execute(text("DROP SCHEMA public CASCADE; CREATE SCHEMA public;"))
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    cfg = Config(os.path.join(here, "alembic.ini"))
    cfg.set_main_option("script_location", os.path.join(here, "alembic"))
    command.upgrade(cfg, "head")


def seed_master(db) -> dict:
    _guard()
    if db.scalar(select(UserAccount).where(UserAccount.college_email == f"admin@{DOMAIN}")):
        raise SystemExit("Demo data already present. Use --reset to start over.")
    roles = {RoleCode(r.code): r.role_id for r in db.scalars(select(Role))}
    cfg = db.get(InstitutionConfig, 1)
    cfg.institution_name = "Demo Institute of Technology (sample data)"
    cfg.week_start_day = 1        # dev convenience; production must be configured by the Admin
    cfg.lunch_boundary = time(14, 0)
    cfg.working_hours_start, cfg.working_hours_end = time(9, 0), time(17, 0)

    ay_old = AcademicYear(label="2025-2026", start_date=date(2025, 7, 1), end_date=date(2026, 6, 30), status="CLOSED")
    ay = AcademicYear(label="2026-2027", start_date=date(2026, 7, 1), end_date=date(2027, 6, 30), status="ACTIVE")
    ce = Department(code="CE", name="Computer Engineering")
    it = Department(code="IT", name="Information Technology")
    db.add_all([ay_old, ay, ce, it])
    db.flush()

    def batch(code, year, parent=None, dept=ce):
        level, div = code.split("-")
        b = Batch(department_id=dept.department_id, code=code, cohort_label=f"{level}-{2027 - year}", division_label=div,
                  program_year=year, parent_batch_id=parent.batch_id if parent else None)
        db.add(b)
        db.flush()
        return b

    batches = {}
    for div in "ABCD":
        parent = batch(f"SE-{div}", 2)
        batches[parent.code] = parent
        for n in range(1, 5):
            batches[f"SE-{div}{n}"] = batch(f"SE-{div}{n}", 2, parent)
    for div in "ABCD":
        parent = batch(f"BE-{div}", 4)
        batches[parent.code] = parent
        for n in range(1, 3):
            batches[f"BE-{div}{n}"] = batch(f"BE-{div}{n}", 4, parent)
    batches["TE-A"] = batch("TE-A", 3)
    batches["IT-SE-A"] = Batch(department_id=it.department_id, code="SE-A", cohort_label="SE-2025", division_label="A", program_year=2)
    db.add(batches["IT-SE-A"])

    for code, name in [("DBMS", "Database Management Systems"), ("COA", "Computer Organization and Architecture"),
                       ("DS", "Data Structures"), ("DSGT", "Discrete Structures and Graph Theory")]:
        db.add(Course(department_id=ce.department_id, course_code=code, name=name))
    for code, floor in [("508", "5"), ("509 old", "5"), ("510", "5"), ("604", "6"), ("605", "6"), ("606-4", "6"), ("607", "6"),
                        ("701", "7"), ("702", "7"), ("702-B", "7"), ("703", "7")]:
        db.add(Room(room_code=code, building="Main Building", floor_label=floor, capacity=60 if not code.startswith("6") else 30,
                    room_type="LAB" if code.startswith("6") else "CLASSROOM"))
    db.flush()

    def account(email, name, *role_codes, status=AccountStatus.ACTIVE):
        u = UserAccount(college_email=f"{email}@{DOMAIN}", display_name=name, password_hash=hash_password(DEMO_PASSWORD),
                        account_status=status, timezone_id="Asia/Kolkata")
        db.add(u)
        db.flush()
        for r in role_codes:
            db.add(UserRole(user_id=u.user_id, role_id=roles[r]))
        db.add(UserPreference(user_id=u.user_id))
        return u

    def staff(email, name, *rcs, dept=ce, code=None, designation=None):
        u = account(email, name, *rcs)
        s = Staff(user_id=u.user_id, department_id=dept.department_id if dept else None, short_code=code, designation=designation)
        db.add(s)
        db.flush()
        return u, s

    admin_u, admin_s = staff("admin", "Asha Admin (demo)", RoleCode.ADMIN, dept=None, designation="Registrar office")
    staff("principal", "Dr. Prem Principal (demo)", RoleCode.PRINCIPAL, dept=None, designation="Principal")
    staff("kkd", "Prof. Kiran K. Desai", RoleCode.HOD, RoleCode.PROFESSOR, code="KKD", designation="HOD, Computer Engineering")
    staff("avn", "Prof. Anita V. Nair", RoleCode.PROFESSOR, code="AVN", designation="Associate Professor")
    staff("pjb", "Dr. Prakash J. Bhatt", RoleCode.PROFESSOR, code="PJB", designation="Professor")
    staff("rhs", "Prof. Rhea H. Shah", RoleCode.PROFESSOR, code="RHS", designation="Assistant Professor")
    staff("ithod", "Prof. Ira T. Hegde (demo)", RoleCode.HOD, RoleCode.PROFESSOR, dept=it, code="ITH", designation="HOD, IT")

    def student(email, name, uid, batch_code):
        u = account(email, name, RoleCode.STUDENT)
        st = Student(user_id=u.user_id, uid=uid, department_id=ce.department_id)
        db.add(st)
        db.flush()
        b = batches.get(batch_code) if batch_code else None
        db.add(StudentAcademicHistory(student_id=st.student_id, academic_year_id=ay_old.academic_year_id, year_of_study=1,
                                      semester=2, department_id=ce.department_id, batch_id=None, status=HistoryStatus.PROMOTED,
                                      effective_from=date(2025, 7, 15), effective_to=date(2026, 7, 1),
                                      confirmed_by_staff_id=admin_s.staff_id, note="Sample prior year"))
        db.add(StudentAcademicHistory(student_id=st.student_id, academic_year_id=ay.academic_year_id,
                                      year_of_study=b.program_year if b else 2, semester=3, department_id=ce.department_id,
                                      batch_id=b.batch_id if b else None, status=HistoryStatus.ACTIVE,
                                      effective_from=date(2026, 7, 1), confirmed_by_staff_id=admin_s.staff_id))
        return u

    student("alice", "Alice Student (SE-A1)", "2025CE001", "SE-A1")
    student("bob", "Bob Student (SE-A2)", "2025CE002", "SE-A2")
    student("chitra", "Chitra Student (SE-C1)", "2025CE031", "SE-C1")
    student("dev", "Dev Student (BE-B2)", "2023CE045", "BE-B2")
    student("newbie", "Neha New (no batch yet)", "2026CE099", None)
    db.commit()
    return {"admin_user_id": admin_u.user_id, "academic_year_id": ay.academic_year_id, "department_id": ce.department_id}


def seed_timetables(db, info: dict) -> None:
    from app.devdata.synthetic import main as make_synthetic
    from app.services.timetables import set_primary
    from app.services.uploads import create_upload
    from app.worker import drain

    out = make_synthetic(tempfile.mkdtemp(prefix="tt-demo-"))
    admin = db.get(UserAccount, info["admin_user_id"])
    ap = load_principal(db, admin)
    data = open(os.path.join(out, "synthetic_timetable.pdf"), "rb").read()
    tt, _, _, _ = create_upload(db, ap, Domain.INSTITUTIONAL, data, "synthetic_timetable.pdf",
                                "SAMPLE — CE timetable AY 2026-27 (synthetic)", info["academic_year_id"], info["department_id"])
    drain()
    db.expire_all()
    set_primary(db, ap, Domain.INSTITUTIONAL, tt.timetable_id)

    alice = db.scalar(select(UserAccount).where(UserAccount.college_email == f"alice@{DOMAIN}"))
    alp = load_principal(db, alice)
    pdata = open(os.path.join(out, "synthetic_timetable.xlsx"), "rb").read()
    ptt, _, _, _ = create_upload(db, alp, Domain.PERSONAL, pdata, "my_timetable.xlsx", "My semester plan (sample)")
    drain()
    db.expire_all()
    set_primary(db, alp, Domain.PERSONAL, ptt.timetable_id)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--reset", action="store_true", help="drop and recreate the schema first (DESTROYS DATA)")
    ap.add_argument("--no-timetables", action="store_true")
    args = ap.parse_args()
    _guard()
    if args.reset:
        reset_database()
    with session_factory()() as db:
        info = seed_master(db)
        if not args.no_timetables:
            seed_timetables(db, info)
    print(f"Demo data ready. Accounts use password {DEMO_PASSWORD!r} (development only):")
    for e in ("admin", "principal", "kkd (HOD+Professor)", "avn", "pjb", "rhs", "ithod", "alice", "bob", "chitra", "dev", "newbie"):
        print(f"  {e.split(' ')[0]}@{DOMAIN}  {e[len(e.split(' ')[0]):].strip()}")


if __name__ == "__main__":
    main()
